### ISSUE TITLE
zzz创建模板没有选项

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#10]
![image](https://user-images.githubusercontent.com/44720525/94354427-7065e400-00ad-11eb-96d3-3066ddb7d6c0.png)

**Comment by xuyang404** [comment]
Use the arrow keys to navigate: ↓ ↑ → ← 
? Select Template: 

No results

**Comment by sohaha** [comment]
因为直接读取 GitHub Api ，估计你那边网络问题读取失败，我加个镜像吧

**Comment by sohaha** [comment]
更新一下 zzz 工具即可

**Comment by xuyang404** [comment]
> 更新一下 zzz 工具即可
好的，谢谢

**Comment by xuyang404** [comment]
> 更新一下 zzz 工具即可

更新了，但是在终端是没问题，在goland里就没有选项了

**Comment by sohaha** [comment]
> > 更新一下 zzz 工具即可
> 
> 更新了，但是在终端是没问题，在goland里就没有选项了

什么系统，检查下网络，然后再试试，只可能网络问题😅
