### ISSUE TITLE
znet.BindStructDelimiter = "_"失效

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#11]
znet.BindStructDelimiter = "_"在最新版本不生效了

**Comment by sohaha** [comment]
没有呀, 你的代码是怎么样的

**Comment by xuyang404** [comment]
> 没有呀, 你的代码是怎么样的

znet.BindStructDelimiter = "_"

**Comment by xuyang404** [comment]
> 没有呀, 你的代码是怎么样的

之前还可以，更新了一下之后就不行了

**Comment by xuyang404** [comment]
> 没有呀, 你的代码是怎么样的

经测试，必须在Engine = znet.New()之前使用znet.BindStructDelimiter = "_"才能生效，但是之前的版本是可以在Engine = znet.New()之后使用的

**Comment by sohaha** [comment]
znet.BindStructDelimiter = "_" 是全局，只能在new之前，
要在new之后：

r:=znet.New()
r.BindStructDelimiter = "_"

因为分组也可以独立设置，

g:=r.Group("/debug")
g.BindStructDelimiter = ""


这块后面文档补充下吧
