### ISSUE TITLE
http包里的的res.ToFile对windows不友好

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#12]
经测试在windows上，如果用res.ToFile保存文件，会报找不到文件的错误，看了源码之后发现下面这段：
        nameSplit := strings.Split(name, "/")
	nameSplitLen := len(nameSplit)
	if nameSplitLen > 1 {
		dir := strings.Join(nameSplit[0:nameSplitLen-1], "/")
		name = zfile.RealPathMkdir(dir) + "/" + nameSplit[nameSplitLen-1]
	}
在windows上，文件路径是用"\"分割的，所以nameSplit := strings.Split(name, "/")会导致在windows上失效

**Comment by sohaha** [comment]
这个是文件需要保存的路径，开发中基本都是 ./xxx 这样的相对保存在项目内，你是使用 c:\xxx 这样？

**Comment by xuyang404** [comment]
> 这个是文件需要保存的路径，开发中基本都是 ./xxx 这样的相对保存在项目内，你是使用 c:\xxx 这样？

我是要将文件保存到一个绝对路径中，所以在windows上是c:\xxx

**Comment by sohaha** [comment]
内置兼容处理完成，更新下版本

其实考虑要跨平台，不建议写平台独有的代码段

**Comment by xuyang404** [comment]
> 内置兼容处理完成，更新下版本
> 
> 其实考虑要跨平台，不建议写平台独有的代码段

就是为了兼容跨平台，所以用了filepath.Join()函数，才会出现这问题

**Comment by sohaha** [comment]
描述下你需要用到 filepath.Join() 的场景

一般而言直接使用 zfile.RealPath() 就行了

**Comment by xuyang404** [comment]
> 描述下你需要用到 filepath.Join() 的场景
> 
> 一般而言直接使用 zfile.RealPath() 就行了

dir = filepath.Join(baseDir, currentDir)
filepath.Join(dir, fileName + ".jpg")

**Comment by sohaha** [comment]
```go
RealPath(baseDir + "/" + "d" + "/" + fileName + ".jpg")

RealPath(strings.Join([]string{baseDir, currentDir,fileName},"/"))+".jpg"
```

这样写是不能满足还是不兼容?

**Comment by xuyang404** [comment]
因为之前不知道有zfile.RealPath()这函数

**Comment by xuyang404** [comment]
> ```go
> RealPath(baseDir + "/" + "d" + "/" + fileName + ".jpg")
> 
> RealPath(strings.Join([]string{baseDir, currentDir,fileName},"/"))+".jpg"
> ```
> 
> 这样写是不能满足还是不兼容?

而且这样写也会担心不兼容windows,因为windows用上的路径是"\"

**Comment by xuyang404** [comment]
> ```go
> RealPath(baseDir + "/" + "d" + "/" + fileName + ".jpg")
> 
> RealPath(strings.Join([]string{baseDir, currentDir,fileName},"/"))+".jpg"
> ```
> 
> 这样写是不能满足还是不兼容?

而且这样写也会担心不兼容windows,因为windows用上的路径是反斜杠

**Comment by sohaha** [comment]
主要是 baseDir 是怎么来的，

RealPath本身就有兼容 反斜杠 的，统一转换成 斜杠

**Comment by xuyang404** [comment]
> 主要是 baseDir 是怎么来的，
> 
> RealPath本身就有兼容 反斜杠 的，统一转换成 斜杠

excuDir, _ := os.Executable()
BaseDir = filepath.Dir(excuDir)

**Comment by xuyang404** [comment]
> > 主要是 baseDir 是怎么来的，
> > RealPath本身就有兼容 反斜杠 的，统一转换成 斜杠
> 
> excuDir, _ := os.Executable()
> BaseDir = filepath.Dir(excuDir)

如果是在windows，路径是C:\a\b\c，统一转换成斜杠就是C:/a/b/c，这路径会不会有问题?

**Comment by xuyang404** [comment]
> 主要是 baseDir 是怎么来的，
> 
> RealPath本身就有兼容 反斜杠 的，统一转换成 斜杠

如果是在windows，路径是C:\a\b\c，统一转换成斜杠就是C:/a/b/c，这路径会不会有问题?

**Comment by sohaha** [comment]
😂 没问题的，RealPath 的本身作用就是为了兼容不同系统

**Comment by xuyang404** [comment]
> 😂 没问题的，RealPath 的本身作用就是为了兼容不同系统

好吧😂

**Comment by sohaha** [comment]
不要想太复杂，反而做了多余的工作量🤣

**Comment by xuyang404** [comment]
> 不要想太复杂，反而做了多余的工作量🤣

好的，谢谢啦
