### ISSUE TITLE
大佬，请问zlsgo的并发性能如何呢?

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#13]
大佬，请问zlsgo的并发性能如何呢?

**Comment by sohaha** [comment]
问的是 znet ? 

大多框架都是基于内置库 net 封装的，彼此基本相差不大，当然框架本身也做了一些优化比如 tree pool 等等，具体你可以测下压。

不过也没什么意义，很多情况瓶颈不在这里。
