### ISSUE TITLE
中间件问题

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#15]
在使用默认中间件的时候遇到个问题，前端报如下错误：
  has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

但是我用如下这种写法却又可以：
```
r.Use(cors.New(&cors.Config{
		Headers:       []string{"Origin", "No-Cache", "X-Requested-With", "If-Modified-Since", "Pragma", "Last-Modified", "Cache-Control", "Expires", "Content-Type", "Access-Control-Allow-Origin"},
	}))
```

然而我只是把默认中间件的源码粘出来，就可以了。这是为什么呢？

**Comment by sohaha** [comment]
使用默认的是怎么样，代码贴一下

**Comment by xuyang404** [comment]
> 使用默认的是怎么样，代码贴一下

```
r.Use(cors.Default())
	r.Group("worker", func(e *znet.Engine) {
		r.GET("/worker/del", delWorker)
		r.GET("/worker/list", workerList)
		r.GET("/worker/search", searchWorker)
	})

	r.Group("job", func(e *znet.Engine) {
		r.POST("/job/save", saveJob)
		r.POST("/job/update", updateJob)
		r.GET("/job/find", findJob)
		r.GET("/job/search", searchJob)
		r.GET("/job/list", jobList)
		r.GET("/job/del", delJob)
		r.GET("/job/kill", killJob)
		r.GET("/job/execute", executeJob)
	})
```

**Comment by xuyang404** [comment]
好像是只要用了分组路由，默认中间件就会失效

**Comment by sohaha** [comment]
全局中间件在分组没问题，

默认的 cors 默认只初始化了 `Domains: []string{}` 
所以你只能 `r.Use(cors.New(&cors.Config{}))` 
不过最新版已经改正过来了，你需要的话可以更新一下)。

**Comment by xuyang404** [comment]
> 全局中间件在分组没问题，
> 
> 默认的 cors 默认只初始化了 `Domains: []string{}`
> 所以你只能 `r.Use(cors.New(&cors.Config{}))`
> 不过最新版已经改正过来了，你需要的话可以更新一下)。

r.Use(cors.Default())在分组里就会有些header头不生效，比如Content-Type

**Comment by sohaha** [comment]
最新版有部分不生效？

**Comment by xuyang404** [comment]
> 最新版有部分不生效？

如果最近几天没更新的话，就是最新版本的

**Comment by sohaha** [comment]
先说清楚是中间件不生效还是header部分不生效。

然后你是用cors.Default()还是cors.New()

**Comment by xuyang404** [comment]
> 先说清楚是中间件不生效还是header部分不生效。

我目前遇到的是header里的部分不生效，比如Content-Type

**Comment by sohaha** [comment]
使用 Default() 还是 New()

**Comment by xuyang404** [comment]
> Default()

 Default()不行，New()正常

**Comment by sohaha** [comment]
😅 所以上面说了，旧版 cors.Default() 的header这些配置没有配置。

你更新新版就有了。

**Comment by xuyang404** [comment]
> 😅 所以上面说了，旧版 cors.Default() 的header这些配置没有配置。
> 
> 你更新新版就有了。

好的，麻烦你了

**Comment by sohaha** [comment]
这是我留下的锅🤫，你先试试，可不可以。

**Comment by xuyang404** [comment]
> 这是我留下的锅🤫，你先试试，可不可以。

刚试了下，没问题
