### ISSUE TITLE
zlog归档的日志不能自动删吗？

### ISSUE THREAD

**Issue by ilaotan** [sohaha/zlsgo#19]
比如15天后自动删除

**Comment by sohaha** [comment]
我们类似日志目录这些一般是通过 corn 去处理的，不过加个自动移除似乎也可行，晚点我更新一版。

**Comment by sohaha** [comment]
@ilaotan 更新了，升级一下版本即可，默认最长保存一个月，如果需要其他时长可自行设置 `zlog.LogMaxDurationDate = xxx`
