### ISSUE TITLE
zshell 命令里有目录带空格就执行不了

### ISSUE THREAD

**Issue by luyuanxun** [sohaha/zlsgo#2]
zshell命令路径带空格错误，如mac打开谷歌浏览器：open /Applications/Google\ Chrome.app

**Comment by sohaha** [comment]
目前是直接已空格做分隔符，后续我优化一下，

暂时可以直接使用 `zshell.ExecCommand(context.Background(), []string{"open", "/Applications/Google Chrome.app"}, nil, nil, nil)`

**Comment by luyuanxun** [comment]
好的，谢谢

**Comment by sohaha** [comment]
@luyuanxun 已支持 zshell.Run("open /Applications/Google\\ Chrome.app")
