### ISSUE TITLE
命令行应用怎么设置 短标识，我没看到有对外暴露的标识？

### ISSUE THREAD

**Issue by DarkiT** [sohaha/zlsgo#20]
命令行应用怎么设置 短标识，类似版本信息的 -V 参数，我没看到有对外暴露的标识？

**Comment by sohaha** [comment]
其实本身是不区分长短选项的，比如 --b 和 -b 是一样的，
可以进一步说说什么情景下的需求吗？
如果有必要，等我身体恢复后，在不影响向下兼容的情况可以尝试支持，或者你也可以发起 PR 😀

**Comment by DarkiT** [comment]
特殊时期，保重好身体，我就是随口问下。Golang新手还达不到发PR的能力，另外我想请教下，使用zlsgo我想注册成守护进程，但是似乎不支持  ./app install -addr=:8181 -dir=/mnt 这种带参数的格式进行注册，主要是不想为几个参数单独再加个配置文件。下面是我写的代码，请问是不是哪里有问题。

`binary, _ := os.Executable()
root := filepath.Dir(binary)

var args []string
if len(os.Args) > 1 {
	for i, v := range os.Args {
		if i <= 1 {
			continue
		}
		args = append(args, v)
	}
}
daemonConfig := &daemon.Config{
	Name:        "ops",
	DisplayName: "ops",
	Description: "测试",
	UserName:    "root",
	WorkingDir:  root,
	Arguments:   args,
}
err := zcli.LaunchServiceRun("ops", "测试", run, daemonConfig)`

**Comment by sohaha** [comment]
正常的, 注册成系统服务是属于严谨的操作, 所以故意不支持动态参数的, 

还是建议使用配置文件, 也没几行的事(反正配置文件不存在也会自动创建), 

```
 package main 

  import (
      "github.com/zlsgo/conf"
      "github.com/sohaha/zlsgo/zlog"
  )


  func main(){
    cfg := conf.New("conf.yml")

    // 设置默认配置
    cfg.SetDefault("prot",6666)

    // 如果配置了默认配置并且配置文件不存在会在当前目录生成一个配置文件
    _ = cfg.Read()
    if err != nil{

    }

    // ... 
    prot := cfg.GetInt("prot")

  }
```
