### ISSUE TITLE
zjson库能处理30000qps的数据吗？

### ISSUE THREAD

**Issue by wthahaha** [sohaha/zlsgo#26]
我的数据量较大，每秒请求30000多次，需要将每个请求中的参数提取出来，不知zjson的性能能满足需求吗

**Comment by sohaha** [comment]
可以, 如果只是单纯的使用 Get 是没反射的, 性能是比直接 Unmarshal 更快的, 另外可以注意下写法 `j.Get("x1.z1").String()` 是比 `j.Get("x1").Get("z1").String()` 更高效

**Comment by wthahaha** [comment]
哦哦，谢谢，我同时需要使用Set方法构造一个新的json，data, _ = zjson.Set(data, "name", "Demo")，Set方法也能处理30000qps的数据量吗

**Comment by sohaha** [comment]
😂 不是问题
