### ISSUE TITLE
请问是否能同时支持操作多个数据库？

### ISSUE THREAD

**Issue by daniel-007** [sohaha/zlsgo#3]
比如，同时支持mysql和sqlite。我的业务场景是从远程的Mysql数据库里读取指定数据，然后保存在本地的sqlite里。该如何配置呢？谢谢。

**Comment by sohaha** [comment]
@daniel-007 创建两个数据库对象，一个 mysql 一个sqlite 不就可以了

**Comment by daniel-007** [comment]
> @daniel-007 创建两个数据库对象，一个 mysql 一个sqlite 不就可以了

@sohaha 感谢回复。嗯，我是指zlsgo-app这个模板项目里，conf.yml 配置里如何配置？
