### ISSUE TITLE
BindQuery方法无法正常使用，传入指针时将会panic

### ISSUE THREAD

**Issue by wetor** [sohaha/zlsgo#30]
在使用znet提供的web功能时，发现 `znet.Context.BindQuery` 无法正确的映射到结构体指针中， `TestContext_BindQuery` 单测单独执行无法通过

具体原因是使用 `TypeOf(&StrcutValue)` 得到的 `reflect.Type` 的 kind 为 `reflect.Pointer`，即入参 `typ`  
使用`typ.NumField()` 时将会得到panic：`panic: reflect: NumField of non-struct type *StrcutValue`
```go
func ForEach(typ reflect.Type, fn func(parent []string, index int, tag string, field reflect.StructField) error) (err error) {
	var forField func(typ reflect.Type, parent []string) error
	forField = func(typ reflect.Type, parent []string) error {
		for i := 0; i < typ.NumField(); i++ {  // <-- panic
			field := typ.Field(i)
			fieldTag, _ := GetStructTag(field)

			err = fn(parent, i, fieldTag, field)
			if err == SkipChild {
				continue
			}

			if err == nil && field.Type.Kind() == reflect.Struct {
				err = forField(field.Type, append(parent, fieldTag))
			}

			if err != nil {
				return err
			}
		}
		return nil
	}

	return forField(typ, []string{})
}
```

简单修复后：
```go
func ForEach(typ reflect.Type, fn func(parent []string, index int, tag string, field reflect.StructField) error) (err error) {
	var forField func(typ reflect.Type, parent []string) error
	if typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	forField = func(typ reflect.Type, parent []string) error {
		for i := 0; i < typ.NumField(); i++ {
			field := typ.Field(i)
			fieldTag, _ := GetStructTag(field)

			err = fn(parent, i, fieldTag, field)
			if err == SkipChild {
				continue
			}

			if err == nil && field.Type.Kind() == reflect.Struct {
				err = forField(field.Type, append(parent, fieldTag))
			}

			if err != nil {
				return err
			}
		}
		return nil
	}

	return forField(typ, []string{})
}
```
顺便发现`ForEachValue`有同样的问题，同样的方式修复

另一种修复方式是在`znet.Context.BindQuery` 中对于`reflect.Pointer` 类型的入参做处理。但是可能还有其他地方存在类似的问题，所以直接修复了最底层的foreach方法。

环境信息：go.1.20.2 windows amd64

（PS1: commit message按照项目样式来的）
（PS2: 顺便对于zfile中提供的几个方法存在疑问，很多方法都忽略了`err`处理，不清楚为什么要这么做？我这边为了保证程序的稳定性所以最终还是自己实现...）

**Comment by wetor** [comment]
https://github.com/sohaha/zlsgo/pull/29

一个简单的修复合并请求，如果作者有别的更优雅的方法可以把pr关了

**Comment by sohaha** [comment]
谢谢你的 PR。

关于 zfile 里忽略掉的要么是不影响或者出现不了的才是🤦🏻‍♀️，还麻烦指出下。

**Comment by wetor** [comment]
> #29
> 
> 一个简单的修复合并请求，如果作者有别的更优雅的方法可以把pr关了

一些底层为syscall的我也不太确定是否会有奇怪的err（如一些 `filepath`的使用），内部逻辑有点复杂。
不过这个`zfile.RealPathMkdir`是有点问题。
```go
func RealPathMkdir(path string, addSlash ...bool) string {
	realPath := RealPath(path, addSlash...)
	if DirExist(realPath) {
		return realPath
	}
	_ = os.MkdirAll(realPath, os.ModePerm)
	return realPath
}
```

这里的`os.MkdirAll(realPath, os.ModePerm)` 可能存在因为权限不足（非windows下很常见）而创建失败的场景，而又返回了预期的`realPath`，会导致后续对这个路径的所有操作均出现问题

**Comment by sohaha** [comment]
这个确实, 因为我们项目大多是在操作程序所在目录, 很少会对系统或其他用户目录操作, 而这个函数主要起一个兼容(不确定文件夹存不存在)作用, 后续我找个时间处理下这种情况吧, 谢谢

**Comment by wetor** [comment]
好的，因为这些方法比较简单，同时我也需要指定权限，所以我就自己封装了一下。只是此项目作为一个通用库感觉这种err还是交给调用方来判断是否舍弃会比较好

既然主要问题已经修复所以我就先关闭此issue了
