### ISSUE TITLE
http可以加入随机指纹吗

### ISSUE THREAD

**Issue by Mr-XiaoLei** [sohaha/zlsgo#33]

**Comment by sohaha** [comment]
随机指纹? 你是想随机 UserAgent ?

```go
zhttp.SetUserAgent(func() string {
  // 返回空表示从内置 UA 列表(zhttp.UserAgentLists)随机一个
  // 或者你自己维护一个列表 ?
  return ""
})
```

**Comment by Mr-XiaoLei** [comment]
ja3、ja4、http2、tls 这种http指纹

**Comment by sohaha** [comment]
这个你可以使用 http.Transport 来处理呀

**Comment by sohaha** [comment]
大部分请求属于接口通讯，
应该用不到，
如果可以请描述下你的应用场景，
有必要我可以弄个扩展包。

**Comment by Mr-XiaoLei** [comment]
JA3指纹又叫做浏览器指纹，它是不会随着你更换 IP 或者 User-Agent 而改变的。而且即使你不使用模拟浏览器，你直接使用 Golang、使用 Python，它们也有自己各自的指纹，并且他们的指纹每次请求也是固定的。只要网站发现某个拥有特定指纹的客户端持续高频率请求网站，它就可以发现你并且把你封掉.

参考：https://yebd1h.smartapps.cn/pages/blog/index?blogId=123881368&_swebfr=1&_swebFromHost=bdlite

**Comment by sohaha** [comment]
这个了解，是问在你项目中，为何需要修改指纹？(总不能做非法爬虫吧🐶

**Comment by Mr-XiaoLei** [comment]
因为现在挺多网站或者风控都有检测指纹从而进行限制，go也有挺多的开源库可以修改指纹。 只是个人不太喜欢引用过多的库，所以才问一下。这个功能对于不是经常使用爬虫的开发者来说确实不是必要的。

**Comment by sohaha** [comment]
<img width="560" alt="image" src="https://github.com/user-attachments/assets/806fa06a-e586-4028-ac8e-24d6825c4caa">

<img width="707" alt="image" src="https://github.com/user-attachments/assets/69181e4d-209f-4172-85c4-fc1443c2c4c0">


想要修改指纹就需要依赖压缩/加密库，感觉需要开个扩展包才行，其他的开源库依赖多吗?

**Comment by Mr-XiaoLei** [comment]
你参考这个：https://github.com/Noooste/azuretls-client，它这个依赖挺多的

**Comment by Mr-XiaoLei** [comment]
太臃肿了，还是喜欢你的库，纯粹只依赖标准库

**Comment by sohaha** [comment]
单纯的随机 JA3 JA4 之类很容易, 但是要完全模拟成各种浏览器的指纹就需要改底层了,所以很多都是分支出go官方的crypto/tls 去实现, 话说正常爬虫中需要完全模拟的需求大吗?
