### ISSUE TITLE
微信模块加载失败

### ISSUE THREAD

**Issue by 914795561** [sohaha/zlsgo#5]
cannot find module providing package github.com/sohaha/wechat:

**Comment by sohaha** [comment]
因为目前只在内部使用，如果需要的话可以整理下发布出来 @914795561

**Comment by 914795561** [comment]
> 因为目前只在内部使用，如果需要的话可以整理下发布出来 @914795561

内部使用，为什么创建模板的时候还有得选微信，文档上也有微信模块的😂

**Comment by sohaha** [comment]
好了, 发布了上 GitHub ,你重新拉一下 `go get github.com/sohaha/wechat`就可以了。

因为代码是需要经过项目考验才能放出来的嘛😆，加上版本迭代之后还没空整理下 WeChat 这个分支的模板。

**Comment by 914795561** [comment]
> 好了, 发布了上 GitHub ,你重新拉一下 `go get github.com/sohaha/wechat`就可以了。
> 
> 因为代码是需要经过项目考验才能放出来的嘛😆，加上版本迭代之后还没空整理下 WeChat 这个分支的模板。

好的，谢谢

**Comment by sohaha** [comment]
模板仓库一同更新了，同时支持 公众号 开放平台 企业微信 所以有些文档没写的例子，建议可以参考模板里的

**Comment by 914795561** [comment]
> 模板仓库一同更新了，同时支持 公众号 开放平台 企业微信 所以有些文档没写的例子，建议可以参考模板里的

好的，非常感谢

**Comment by 914795561** [comment]
配置文件可以用ini吗

**Comment by 914795561** [comment]
我试了下，好像读取不到配置文件........

**Comment by sohaha** [comment]
目前 ini 使用是有问题的，如果只是习惯 ini 的格式，建议可以试试 toml ，两者看起来相差不多，

把现在的配置文件 conf.yml 删除，然后在根目录建立一个 conf.toml 的空文件，直接 `go run .` 之后会自动给配置文件写入默认配置

![image](https://user-images.githubusercontent.com/18098083/91942178-116eb280-ed2d-11ea-8046-3a743099c7ad.png)

如果实在只能使用 ini 那只能等晚点有时间再去 fix 了 :)

**Comment by 914795561** [comment]
现在的问题是这样的，我用ide跑，无论是yml还是ini都读取不了，我用zzz watch跑的话就两者都能读取

**Comment by 914795561** [comment]
而且，无论我用哪种方式跑，我打印cfg.GetAll()都是空，但是用zzz watch跑，虽然打印cfg.GetAll()是空，但却能将读取到的配置映射到结构体

**Comment by sohaha** [comment]
其实是读取到的，因为本身支持安装成系统进程，所以配置文件读取的路径是程序所在的路径，

ide 跑生成的程序不是项目的路径，所以读取到的是生成的程序的临时路径里的那个配置文件。

而 zzz watch 执行的命令把程序编译到项目根目录然后执行的（ide 也可以配置下先编译再执行，具体看下 zzz-watch.yaml ）。

如果不考虑进程守护的话，修改下 global/z_conf.go 即可

```go
func Init() { // 在这里加下下面这行代码
zfile.ProjectPath, _ = filepath.Abs(".")
```

**Comment by 914795561** [comment]
那cfg.GetAll()打印出来一直是空map是正常的吗

**Comment by sohaha** [comment]
看在哪个位置打印，如果是在先于设置默认配置之前是正常的。

配置是步骤是： 读取默认配置 -》 读取配置文件 -》 映射结构体

**Comment by 914795561** [comment]
噢噢，我就是在读取默认配置之前打印的😂

**Comment by 914795561** [comment]
微信模块是只实现了ticket、token、auth、reply等几个模块是吧，其他的如发模板、发文、素材之类的我翻了下都没看到

**Comment by sohaha** [comment]
😂 只要有 token 之后微信所有接口不都是请求一下就好了嘛，
微信接口本来麻烦的不同的点主要在于 token 的获取和储存而已，
至于发送模板什么的数据使用wechat.FormatMap2XML包裹下就可以了。

**Comment by 914795561** [comment]
为什么master模板比wechat模板复杂那么多😂

**Comment by sohaha** [comment]
复杂了?  主要是在配置这块增强了扩展性

**Comment by 914795561** [comment]
就是配置那块，看得头晕眼花也没看懂😂

**Comment by sohaha** [comment]
里面做了分离方便集成测试和项目初始化与配置

扩展方式：
https://docs.73zls.com/zls-go/#/a2d71e80-15ce-418c-b2aa-442866717677

**Comment by 914795561** [comment]
请问db_type是none的时候是什么意思呢

**Comment by 914795561** [comment]
为什么在zzz-watch.yaml里面的types加上.yml，watch就会一直重启呢

**Comment by sohaha** [comment]
要想 watch 配置文件看 z_conf.go 里面有注释掉的 setWatchConf 方法 

至于为什么会一直"重启", 仔细看终端信息,
因为项目启动之后会更新一次配置文件,
你把配置文件也监听那么->死循环

**Comment by 914795561** [comment]
但是微信模板好像不会

**Comment by 914795561** [comment]
而且setWatchConf中data和reloadConfFn都是没有定义的

**Comment by sohaha** [comment]
新模板才支持完全独立的配置扩展

监听配置实际项目中基本用不到, 如果实在要在真实项目中用要处理很多东西,利弊权衡, 

setWatchConf 是供参考,要根据实际情况处理呀

**Comment by 914795561** [comment]
master模板的定时任务好像并没有能执行
