### ISSUE TITLE
模板问题

### ISSUE THREAD

**Issue by 914795561** [sohaha/zlsgo#6]
请问有什么办法可以创建旧app模板吗

**Comment by sohaha** [comment]
不使用 zdb 是因为这个当前只支持直接写 sql , 不是完整的 orm , 比较适合在接入其他项目或者需要对 sql 进行审核的项目。

如要建立旧的可以拉下 wechat-old 然后把微信模块去掉

**Comment by 914795561** [comment]
> 不使用 zdb 是因为这个当前只支持直接写 sql , 不是完整的 orm , 比较适合在接入其他项目或者需要对 sql 进行审核的项目。
> 
> 如要建立旧的可以拉下 wechat-old 然后把微信模块去掉

好的，谢谢
