### ISSUE TITLE
c.Bind无法绑定嵌套结构体

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo#7]
当客户端传过来json的时候，用zjson.Unmarshal可以将json解析到自定义的嵌套结构体，但是用c.Bind就不行

**Comment by sohaha** [comment]
这个问题已经修复的了，只是还没发布，晚点找个时间发布下

**Comment by 914795561** [comment]
还有，跨域中间件也是有问题的，代码写的是判断到option就返回403，这样客户端是跨不了域的

**Comment by sohaha** [comment]
@914795561 已经更新，新的支持指定域名，支持模糊匹配

**Comment by 914795561** [comment]
> @914795561 已经更新，新的支持指定域名，支持模糊匹配

我已经创建好了模板，该如何更新？

**Comment by sohaha** [comment]
`go get -u github.com/sohaha/zlsgo`

或者修改下 go.mod 里的版本 再重新 go build 也会更新

**Comment by 914795561** [comment]
> `go get -u github.com/sohaha/zlsgo`
> 
> 或者修改下 go.mod 里的版本 再重新 go build 也会更新

好的，谢谢

**Comment by 914795561** [comment]
更之后c.Bind的问题好像还存在

**Comment by 914795561** [comment]
而且经过我的测试，跨域代码写在中间件，如果没有在路由中定义options方法的话，根本不起作用

**Comment by sohaha** [comment]
已 fix，麻烦再更新一下。

options 方式是个问题，更新了一下文档，你参考下

https://docs.73zls.com/zls-go/#/9ac3d419-eac7-4e67-a997-122dd997b165?id=%e8%b7%a8%e5%9f%9f%e8%af%b7%e6%b1%82

**Comment by 914795561** [comment]
> 已 fix，麻烦再更新一下。
> 
> options 方式是个问题，更新了一下文档，你参考下
> 
> https://docs.73zls.com/zls-go/#/9ac3d419-eac7-4e67-a997-122dd997b165?id=%e8%b7%a8%e5%9f%9f%e8%af%b7%e6%b1%82

我注册的就是全局中间件，在RegisterMiddleware里面注册的，会出现options问题，但是我在全局预处理里面写的话就不会有options问题

**Comment by sohaha** [comment]
更新之后应该不会，因为现在全局中间件就算找不到路由也会执行

**Comment by 914795561** [comment]
> 更新之后应该不会，因为现在全局中间件就算找不到路由也会执行

好的，我试试

**Comment by 914795561** [comment]
我更新之后，c.Bind的问题还是存在，我更新之后的版本是v0.1.56

**Comment by 914795561** [comment]
还有，跨域中间件能否再灵活一点，让Access-Control-Allow-Methods、Access-Control-Allow-Credentials、Access-Control-Allow-Headers、Access-Control-Allow-Origin这几个都可以自定义内容呢

**Comment by 914795561** [comment]
> 你的结构体是怎么样的，可以发出来看看嘛？

type AddManyReqData struct {
	Appid    string   `json:"appid"`
	Appids   []AppInfo  `json:"appids"`
	Articles []Articles `json:"articles"`
}

type AppInfo struct {
	Label   string `json:"label"`
	Id      string `json:"id"`
	Appid   string `json:"appid"`
	HeadImg string `json:"head_img"`
}

type Articles struct {
	Author             string `json:"author"`
	Content            string `json:"content"`
	Content_source_url string `json:"content_source_url"`
	Digest             string `json:"digest"`
	NeedOpenComment    string `json:"need_open_comment"`
	OnlyFansCanComment string `json:"only_fans_can_comment"`
	ShowCoverPic       string `json:"show_cover_pic"`
	ThumbMediaId       string `json:"thumb_media_id"`
	ThumbUrl           string `json:"thumb_url"`
	Title              string `json:"title"`
	Url                string `json:"url"`
}

**Comment by sohaha** [comment]
绑定的原来是切片, 暂时没什么好的办法, 
因为多级的反射性能消耗有点高，有点得不偿失, 
如果后面有什么好办法再跟进吧，或者你有什么好的建议也欢迎 PR 。

目前只能手动赋值:
```go
		json,_:= c.GetJSONs()
		var appids []AppInfo
		json.Get("appids").ForEach(func(key, value zjson.Res) bool {
			appinfo := AppInfo{}
			err := value.Unmarshal(&appinfo)
			if err != nil {
				c.Log.Error(err)
				return false
			}
			appids = append(appids,appinfo)
			return true
		})
```

**Comment by 914795561** [comment]
我目前是这样写的：
       raw,err := c.GetDataRaw()
	zutil.CheckErr(err)

	err = zjson.Unmarshal(raw, &datas)
	zutil.CheckErr(err)

**Comment by 914795561** [comment]
zhttp.Post(url, zhttp.File(img)) 返回的res无论用什么方法，获取到的数据都是空，但实际上是有数据的

**Comment by sohaha** [comment]
> 我目前是这样写的：
> raw,err := c.GetDataRaw()
> zutil.CheckErr(err)
> 
> ```
> err = zjson.Unmarshal(raw, &datas)
> zutil.CheckErr(err)
> ```

也可以，在于先验证数据还是后验证

**Comment by sohaha** [comment]
> zhttp.Post(url, zhttp.File(img)) 返回的res无论用什么方法，获取到的数据都是空，但实际上是有数据的

是请求拿不到数据还是接收不到文件，单元测试是可以的

你是怎么使用的

**Comment by 914795561** [comment]
> > zhttp.Post(url, zhttp.File(img)) 返回的res无论用什么方法，获取到的数据都是空，但实际上是有数据的
> 
> 是请求拿不到数据还是接收不到文件，单元测试是可以的
> 
> 你是怎么使用的

就是调用zhttp.Post(url, zhttp.File(img)) ，然后返回的res无论用什么方法都无法获取响应的数据

**Comment by 914795561** [comment]
获取到到都是空

**Comment by sohaha** [comment]
到底是上传文件获取不到还是上传成功了返回不了数据？

**Comment by 914795561** [comment]
我请求到是微信的上传素材图片的接口，代码如下：
res, _  := zhttp.Post("https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN ", zhttp.File("文件路径"))
fmt.Println(res.String()) //结果是空

**Comment by sohaha** [comment]
../../README.md  这路径真的对吗？
go 和 PHP 之类不同，是以编译后文件所在路径为根目录的

**Comment by 914795561** [comment]
> ../../README.md 这路径真的对吗？
> go 和 PHP 之类不同，是以编译后文件所在路径为根目录的

这是在单元测试中跑的代码，不要当真，我只是想说，这样的形式去跑得到的res返回值是空的😂

**Comment by 914795561** [comment]
res,err := zhttp.Post("https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN", zhttp.File("../../README.md"))
if err != nil {
fmt.Println(err)
return
}

fmt.Println("res", res.String()) //返回是空

上面这个问题好像是因为微信返回了412状态码，但是就是不知道为什么它会返回412，我也postman请求不会有这样的问题

**Comment by 914795561** [comment]
刚刚我换了我自己之前写的一个http请求库，也是没有问题的

**Comment by sohaha** [comment]
这应该是参数问题，我晚点看看，现在在外面。

印象中微信这里好像有个坑。

**Comment by 914795561** [comment]
好的，麻烦你了，顺便提个建议，zhttp.File()希望可以把字段名放出来让使用者自定义，我看了下源码，这里的字段名是写死media的，这样如果碰到别的业务可能不合理

**Comment by sohaha** [comment]
字段名其实可以直接 &zhttp.FileUpload{} 来定义, 

无法上传的问题想起来了,

https://github.com/sohaha/zlsgo/issues/8

今天都没机会碰电脑, 我晚点修复下同时加个支持直接自定义字段名的吧

**Comment by 914795561** [comment]
> 字段名其实可以直接 zhttp.FileUpload{} 来定义,
> 
> 无法上传的问题想起来了,
> 
> 具体: #8
> 
> 今天都没机会碰电脑, 我晚点修复下同时加个支持直接自定义字段名的吧

好的，麻烦您了

**Comment by sohaha** [comment]
> > 字段名其实可以直接 zhttp.FileUpload{} 来定义,
> > 无法上传的问题想起来了,
> > 具体: #8
> > 今天都没机会碰电脑, 我晚点修复下同时加个支持直接自定义字段名的吧
> 
> 好的，麻烦您了

关闭分块已经好了, 目前 zhttp.File 也支持直接传字段名了

跨域中间件 cors 也支持自定义各种 header

你更新下就好.


wechat 包也建议更新一下, 追加了两个方法, 直接使用内部的 http 方法默认就是关闭分块了

**Comment by xuyang404** [comment]
> > > 字段名其实可以直接 zhttp.FileUpload{} 来定义,
> > > 无法上传的问题想起来了,
> > > 具体: #8
> > > 今天都没机会碰电脑, 我晚点修复下同时加个支持直接自定义字段名的吧
> > 
> > 
> > 好的，麻烦您了
> 
> 关闭分块已经好了, 目前 zhttp.File 也支持直接传字段名了
> 
> 跨域中间件 cors 也支持自定义各种 header
> 
> 你更新下就好.
> 
> wechat 包也建议更新一下, 追加了两个方法, 直接使用内部的 http 方法默认就是关闭分块了

好的，谢谢大佬

**Comment by sohaha** [comment]
2021-01-25 14:19 已支持嵌套结构体切片

**Comment by sohaha** [comment]
支持任意格式的 json bind，并且进一步性能优化
