### ISSUE TITLE
zhttp 支持关闭 chunke

### ISSUE THREAD

**Issue by sohaha** [sohaha/zlsgo#8]
虽然分块可以提高效率，但是微信 Api 不支持分块编码🤦‍♂️

**Comment by xuyang404** [comment]
大佬，我想请教个问题，为什么我在debug页面每刷新一次，内存分配次数和内存释放次数就往上涨一次呢

**Comment by sohaha** [comment]
> 大佬，我想请教个问题，为什么我在debug页面每刷新一次，内存分配次数和内存释放次数就往上涨一次呢

正常的. 每次访问页面代码不就执行了,执行了就有分配了呀

**Comment by sohaha** [comment]
Done

**Comment by xuyang404** [comment]
> > 大佬，我想请教个问题，为什么我在debug页面每刷新一次，内存分配次数和内存释放次数就往上涨一次呢
> 
> 正常的. 每次访问页面代码不就执行了,执行了就有分配了呀

那各种内存使用量和总分配内存，在下次GC之前一直会增加是吗

**Comment by sohaha** [comment]
是一直增的,那不是当前使用内存

**Comment by xuyang404** [comment]
> 是一直增的,那不是当前使用内存

当前内存使用量也不是？

**Comment by sohaha** [comment]
总分配不是, 当前内存使用量是。

如果当前内存使用量一直大量增长没有减少过，那么要检查你代码是不是内存泄漏了。

**Comment by xuyang404** [comment]
> 总分配不是, 当前内存使用量是。
> 
> 如果当前内存使用量一直大量增长没有减少过，那么要检查你代码是不是内存泄漏了。

一直刷新就会缓慢增长，但是好像没见过减少

**Comment by sohaha** [comment]
截图看看,

试试跑一段时间后再看,然后对比下

**Comment by xuyang404** [comment]
![image](https://user-images.githubusercontent.com/44720525/92584761-9ece7b80-f2c6-11ea-97c7-ff689982a374.png)

**Comment by xuyang404** [comment]
> 截图看看,
> 
> 试试跑一段时间后再看,然后对比下

刚才隔了一段时间，的确少了

**Comment by xuyang404** [comment]
有办法知道下次GC时间吗？

**Comment by sohaha** [comment]
没什么意义, 达到回收量 或者 两分钟

**Comment by xuyang404** [comment]
> 没什么意义, 达到回收量 或者 两分钟
噢噢，这样啊，谢谢解答
